### ISSUE TITLE
New version on PyPi

### ISSUE THREAD

**Issue by exploide** [Alir3z4/cmsplugin-simple-markdown#11]
Hey, I'm wondering if you are going to publish a new version of this nice plugin on PyPi. After you merged my PR which made the plugin work with recent versions of django-cms, it would be nice to have the ability to install this package easily via pip :sunglasses:

**Comment by Alir3z4** [comment]
Hey, sure.
I'll be releasing soon.

**Comment by Alir3z4** [comment]
@exploide The new version 1.6 with your latest changes is on pypi now:
https://github.com/Alir3z4/cmsplugin-simple-markdown/releases/tag/1.6

Thanks for the great contributions.

**Comment by exploide** [comment]
Awesome, thank you :)
